dist: focal

language: python

python:
  - "3.11"

branches:
  only:
    - master

services:
  - docker

before_script:
  - cd images/pyodbc
  - git fetch --tags
  - git config --global user.name "Brother"
  - git config --global user.email "bot@laudio.com"

  # Generate .env.test file
  - cp .env.example .env.test
  - export $(egrep -v '^#' .env.test | xargs)

script:
  # Build docker images
  - make clean build

  # Spin up a mssql, pg & mysql database server containers
  - docker compose up -d
  - sleep 20s

  # Run tests
  # Publish image to registry if merged into master.
  - make test
  - make lint-examples

  # List docker images that are built (Just for information.)
  - docker images laudio/*

  - cd ../pyodbc-sqlcmd

  # Generate .env.test file
  - cp .env.example .env.test
  - export $(egrep -v '^#' .env.test | xargs)

  - make clean build
  - make test

after_script:
  # Stop the running containers
  - docker compose down
